### ISSUE TITLE
Duped comment section

### ISSUE THREAD

**Issue by SMEDjs** [daniellwdb/daniellwdb#26] opened 2022-07-27 11:01 UTC
### There is 2 comments section, I realised that after putting a comment from utterances (daniell.dev) and a comment from the github website issues section

at https://daniell.dev/blog/my-thoughts-on-working-as-a-consultant

how to redo:
-Put a comment from the https://daniell.dev/blog/my-thoughts-on-working-as-a-consultant page
-Put a comment from the github issues https://github.com/daniellwdb/daniellwdb/issues/25

images: 

PC - low zoom
![image](https://user-images.githubusercontent.com/61847310/181230798-a26a5395-621c-41a9-b4af-d6ce7b6bff39.png)

mobile
![image](https://media.discordapp.net/attachments/678596723022626863/1001806256811548672/Screenshot_20220727-130015_Chrome.jpg?width=336&height=674)

**Comment by daniellwdb** [comment] 2022-07-27 11:13
Hi, thanks for this issue! I don't think I have much control over this since this is all powered by utterances. I could check some issues there

**Comment by daniellwdb** [comment] 2022-09-02 19:50
Closing since the issue is on utterances side and it doesn't seem to appear constantly

**Closed by daniellwdb** 2022-09-02 19:50 UTC
Labels: bug
